### ISSUE TITLE
[DesignProposal]: Dag IR support DataCollection with schema

### ISSUE THREAD

**Issue by zhujiming** [towhee-io/towhee#1559]
### Background and Motivation

triton server support schema

### Design

dag info add some information
every node add input_info、output_info.
it most likely the picture.
<img width="1530" alt="image" src="https://user-images.githubusercontent.com/18031320/178724612-f5bd3de1-ceb7-4207-8433-c5a199035aa4.png">

**Comment by zhujiming** [comment]
change input_info as a list of tuples
![image](https://user-images.githubusercontent.com/18031320/178746488-2a76ec08-f1f9-44b7-b691-279e88d90a9a.png)

**Comment by filip-halt** [comment]
Why would we need to include the function in the input info? It would require a separate dict to track all functions and their corresponding schema name. Since the schema names all have to be unique, we can drop the function from the tuple.

**Comment by filip-halt** [comment]
Futhermore, one issue found with current scheme indexing. If we have a generator function, lets say a glob that outputs two columns, glob[(path1, path2)](), the corresponding index in the system will be (path1, path2), which looks exactly as if we did image_decode[path, image], which would result in index (path, image). In this case, the engine will think that glob has an input of path1 and output of path2, instead of only having an output of path1 and path2.

**Comment by junjiejiangjjj** [comment]
We only need to support the DC which starts with `dummy_input` ends with `as_function`
