### ISSUE TITLE
[Bug]: ImportError: cannot import name 'accelerate' from 'towhee.dc2'

### ISSUE THREAD

**Issue by suforme** [towhee-io/towhee#2347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

import towhee
(towhee.dc['text'](["hello,world."])
            .text_embedding.transformers['text', 'vec'](model_name="bert-base-cased")
            .show())

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):v0.9.0
- OS(Ubuntu or CentOS):windows10
- CPU/Memory:intel i3-8100
- GPU:
- Others:
```

**Comment by suforme** [comment]
python 3.10.9

**Comment by jaelgu** [comment]
@suforme Fixed. Please clean cache `~/.towhee/operators/text-embedding/transformers` and re-try your code.

**Comment by JieMEI1994BackUp** [comment]
~/.towhee/operators/image-embedding has the same problem which con NOT be fixed by just clean and re-try

**Comment by zhenzi0322** [comment]
![image](https://user-images.githubusercontent.com/34839719/208343133-af9e12bc-76c5-487c-82f9-3602fb07ff63.png)

**Comment by zhenzi0322** [comment]
The problems are as follows:

![image](https://user-images.githubusercontent.com/34839719/208343290-6f079b7d-dc0f-4c42-aa41-82d24ebfffab.png)

![image](https://user-images.githubusercontent.com/34839719/208343384-9f64caef-3d86-4b74-8d74-d802b0b8955b.png)

Same version 0.9.0
![image](https://user-images.githubusercontent.com/34839719/208343449-26ca7a8c-d838-4e38-8a4e-872c363bb1ef.png)

**Comment by hyyz17200** [comment]
Yesterday I had a similar issue too. I ran the official Milvus reverse image search Bootcamp and got the same Error. 

It may be an issue on the towhee server side because I backup the docker containers I had succeeded in before. Even I restore the backup, and I still get the "towhee.dc2" Error.

Today, just now, I ran again, and the issue is gone.

So, as far as I know, it should be a towhee server configuration issue. And they may have fixed it now.
