### ISSUE TITLE
[Bug]: Hub does not need an account to push.

### ISSUE THREAD

**Issue by Chiiizzzy** [towhee-io/towhee#556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In my mac: 
I don't need an account to push my local changes to any repo, which means anyone can modify others repo easily. We should avoid such case and verify the users before they can push their changes to the repo.
In ubuntu:
I need to enter user name and password before I can push my changes to the repo, which should be the correct case. Anyone  has any idea on this? 

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by filip-halt** [comment]
Do we have a plan for this?

**Comment by shiyu22** [comment]
I think it's because the Mac records the key in **keychain access**, which you can remove so that the password is required when pushing.

1. Logout towhee account and remove form **keychain access**.
First run `towhee logout` command, (required on Mav)then open **keychain access**, search *towhee* then to remove the account.


![image](https://user-images.githubusercontent.com/53459423/160521588-da2344fa-b8bf-425c-94da-9c3b5c666ee8.png)
2. Login and you can push without account and PWD.
Run `towee login` command to login towhee hub account, and you can also run `towhee whoami` to see which account you have logged in.
